### ISSUE TITLE
Accessing cx via withStyles

### ISSUE THREAD

**Issue by alexplumb** [garronej/tss-react#117]
Looking through the documentation and code for withStyles, I don't see any way to get access to the `cx` function. Is there some way to use this in a class component?

I could get around this if I could import `createCssAndCx` but this isn't available as an export as far as I can tell.

**Comment by garronej** [comment]
@alexplumb,  

Hold on, I got you.

**Comment by garronej** [comment]
You can create a `cx` standalone function as long as you explicitely provide a cache to `createMakeAndWithStyles()`:  

https://docs.tss-react.dev/cache#specify-the-cache-at-inception  

If you do so you can use the same cache for creating a `cx` function like:   

tssExports.ts
```typescript
import createCache from "@emotion/cache";
import { createCssAndCx } from "tss-react/cssAndCx";

const cache = createCache({
  "key": "custom"
});

export const { makeStyles, withStyles, useStyles } = createMakeAndWithStyles({
    useTheme,
    cache
});

export const { css, cx } = createCssAndCx({ cache });
```  

If you go the custom cache route you want to make sure that your custom styles overrides the MUI default styles.  
For that you have two option, provide an other cache to MUI with `"prepend": true` or provide the cache tou are using with TSS.  

```tsx

 import { createRoot } from "react-dom/client";
import { CacheProvider } from "@emotion/react";
import { cache } from "./path/to/tssExports";

 const container = document.getElementById('app');
 const root = createRoot(container!); 
 root.render(
    <CacheProvider value={cache}>
            <App />
    </CacheProvider>
);
```

Hope it helps,  

Best regards,  

PS: You have to upgrade to `tss-react` v4.1.4 for it to work.

**Comment by alexplumb** [comment]
I'm suddenly compelled to refactor the one component in my codebase that needs this solution.

**Comment by garronej** [comment]
> I'm suddenly compelled to refactor the one component in my codebase that needs this solution.  

I get how this can be frustrating, trust that I do my absolute best to provide an uncompromising DX but in this specific usecase, with a class component this is the only way I see to make it work.  

I need to know the contextual cache to be able to implement the `cx()` function and since it's impossible to use hooks in a class component the only way is to provide the cache explicitely.  

If what's bothering you is having to import from `../../../tssExport` instead of `tss-react/mui` you could create a `tss-react_mui.ts` file in your `src/` dir and use `"baseDir": "src"` in your `tsconfig.json`. See [here](https://github.com/garronej/tss-react/blob/2d2c57c246ab8cb374a9324a47a5d3dd9464da5e/README.md?plain=1#L124-L135)  

This way you would just have to change all the `import {makeStyles} from "tss-react/mui"` by `import { makeStyles } from "tss-react_mui";`  

I let you decide how you want to procede.  

I'll close this isue now because there is not much I can do.  

Best regards,    

PS: I tried and see if `@emotion/react` and `@emotion/css` would share the same default cache.  Unfortunately it isn't the case so I am confident in saying that there is no other solution than the one I offered :/
