### ISSUE TITLE
TSS version, Emotion, MUI & Gatsby

### ISSUE THREAD

**Issue by Antholife** [garronej/tss-react#130]
Hello,

Unfortunately your solution for Gatsby is not functional under TssReact 4.4.4, indeed I use Gatsby for static pages,
This breaks: import { getTssDefaultEmotionCache } from 'tss-react';

It's not available in the latest version.. so I'm stuck with MUI, Emotion, TSS, Gatsby.. Im lost

Currently I am getting this error..

     `See our docs page for more info on this error: https://gatsby.dev/debug-html
      ownerState.variant === 'contained' && ownerState.color !== 'inherit' && {
       >     backgroundColor: (theme.vars || theme).palette[ownerState.color].dark,     
      '@media (hover: none)': {
       backgroundColor: (theme.vars || theme).palette[ownerState.color].main
      WebpackError: TypeError: Cannot read properties of undefined (reading 'dark')
      - Button.js:100 
        [HostingV3]/[@mui]/material/esm/Button/Button.js
      - createStyled.js:180 
        [HostingV3]/[material]/[@mui]/system/esm/createStyled.js
      - emotion-serialize.esm.js:139 
        [HostingV3]/[@emotion]/serialize/dist/emotion-serialize.esm.js
      - emotion-serialize.esm.js:253 
        [HostingV3]/[@emotion]/serialize/dist/emotion-serialize.esm.js
      - emotion-styled-base.esm.js:140 
        [HostingV3]/[@emotion]/styled/base/dist/emotion-styled-base.esm.js
      - emotion-element-3838ba9e.esm.js:59 
        [HostingV3]/[@emotion]/react/dist/emotion-element-3838ba9e.esm.js
      `

How do you make it all work together today?

**Comment by garronej** [comment]
Hi @Antholife,  
Sorry for the outdated doc, I'm having a look.

**Comment by garronej** [comment]
Hey @Antholife,   

I submited a PR to update the demo setup: https://github.com/Deckstar/gatsby-tss-example/pull/2  
Here is the Diff: https://github.com/Deckstar/gatsby-tss-example/pull/2/files  

It's simpler to get it working in v4 because TSS doesen't need to use a different cache than MUI.  

If you still have problem, please tell me, to make TSS and MUI use a different cache like described here: https://docs.tss-react.dev/troubleshoot-migration-to-muiv5-with-tss
