### ISSUE TITLE
Invalid type for withStyles

### ISSUE THREAD

**Issue by Akatroj** [garronej/tss-react#205]
When using `withStyles`, I get a typescript error saying `Property 'root' is missing in type '{ title: { margin: string; }; }' but required in type '{ root: CSSObject; }'.ts(2345)`. It disappears if I add an empty object under `root` key, but  I think this is incorrect, because when using `makeStyles`, I don't need to include a `root` key.

<img width="1196" alt="image" src="https://github.com/garronej/tss-react/assets/46789820/19853382-fd1f-4f24-ad0d-afc6bf6367f8">

**Comment by Akatroj** [comment]
would also be pretty cool if there was a utility type for working with class components in Typescript, sth like `WithStyles<Props>` that can add the 'classes' prop onto the Props type.

**Comment by garronej** [comment]
Hello @Akatroj,  

This is the expected behavior. The classes you use should be declared on you component props type declaration.  
Checkout the documentation for more infos:  https://docs.tss-react.dev/api/withstyles  

And regarding your other point. withStyles can be used with class components:  

<img width="903" alt="image" src="https://github.com/garronej/tss-react/assets/6702424/9126ee09-fd74-4e19-ba96-14d064ef3224">

Hope it helps.

**Comment by Akatroj** [comment]
Thanks! I thought this would work like `connect` from react-redux, where the props are inferred from the object returned by `mapStateToProps` function. I guess your approach of manually declaring the classes used and validating against them makes sense to allow for overriding.

Thanks for clarifying!

**Comment by garronej** [comment]
It's the only way I say to make this API proerly typesafe.  

But, by the way, unless you are migrating a big codebase or working with classes component you might want to use the modern TSS API. https://docs.tss-react.dev/api/tss-usestyles it's better in every ways :)
