### ISSUE TITLE
Issues while using Yarn 3

### ISSUE THREAD

**Issue by AugustinasMK** [garronej/tss-react#36]
Hi, while building our project we get these errors from Yarn 3 with PnP.

```
./.yarn/__virtual__/tss-react-virtual-f99a3cd5a8/0/cache/tss-react-npm-2.0.2-7ea9c3ac36-21cc281768.zip/node_modules/tss-react/cssAndCx.js
Module not found: tss-react tried to access @emotion/serialize, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

```
and 
```
./.yarn/__virtual__/tss-react-virtual-f99a3cd5a8/0/cache/tss-react-npm-2.0.2-7ea9c3ac36-21cc281768.zip/node_modules/tss-react/cssAndCx.js
Module not found: tss-react tried to access @emotion/utils, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

```

While this can be fixed via .yarnrc.yml, I would appreciate it if you could add these as dependencies to your package.

**Comment by garronej** [comment]
Thank you for reporting. It's really a pain that emotion splits itself into tiny little bundles instead of using three shaking.  
I can't just add them as dependency, I should add them as peer dependency and make everyone install them explicitly when really they are just part of @emotion/react😫.  

I will try with optionalPeerDependency... you tell me if it does the trick

**Comment by garronej** [comment]
@AugustinasMK I have published a new version, you tell me if it does the trick.

**Comment by AugustinasMK** [comment]
@garronej seems to work fine now. Thanks ❤
