### ISSUE TITLE
3.6.2 changelog

### ISSUE THREAD

**Issue by Semigradsky** [garronej/tss-react#79]
> Make csstype an expliciy dependency (for yarn 2+)

As I see you added dependency in https://github.com/garronej/tss-react/commit/90922dd18498564a9758df10a8df44259ab9e483 but removed it in https://github.com/garronej/tss-react/commit/0733f0a1562e7a27fb6ed98321f2f8e4d362ad58

**Comment by garronej** [comment]
Hi @Semigradsky,  
Yes sorry, the changelog is generated autmatically with commit messages.  
I fist added `csstypes` because it was used explicitely and not present in dependency which is problematic for yarn plug n play.  
I then applied what [you suggested](https://github.com/garronej/tss-react/issues/79), importing the types from `@emotion/serialize` instead of copying them; after that, `csstypes` was no longer used explicitely.
